In [2]:
import pandas as pd

In [3]:
pd.read_json("train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [4]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-18,1776470401,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-18,1776470401,0.0395
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-18,1776470401,0.6910
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-18,1776470401,0.8700
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-18,1776470401,4.0300
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-18,1776470401,2.5600
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-18,1776470401,0.1760
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-18,1776470401,0.2060
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-18,1776470401,0.2710
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-04-18,1776470401,0.2710

In [9]:
!python -m pip install mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql-connector-python in C:\Users\MY\AppData\Roaming\Python\Python313\site-packages (9.6.0)

WARNING: Ignoring invalid distribution ~ip (C:\Users\MY\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\MY\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\MY\AppData\Roaming\Python\Python313\site-packages)
WARNING: Ignoring invalid distribution ~ip (C:\Users\MY\AppData\Roaming\Python\Python313\site-packages)

In [10]:
import mysql.connector

In [12]:
conn = mysql.connector.connect(
    host='localhost',
    user='root',
    password='Bilal@2025',   # put your real password here
    database='world'
)

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

In [ ]:
print(conn.is_connected())

In [ ]:
df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)